export const characterList = {
    dummy: {
      id: 'dummy',
      name: "Dummy",
      health: 200,
      maxHealth: 200,
      shield: 0,
      damage: 0,
      speed: 0,
      experience: 0,
      level: 1,
      image: '/CharacterImage/dummy.png',
      skills: ['basicAttack'],
      passives: [],
      status_effects: [],
      playable: false,
      money_drop: 0,
      experience_drop: 0,
    },
    knight: { 
        id: 'knight', 
        name: "Knight", 
        health: 80,
        maxHealth: 80,
        shield: 0,
        damage: 15, 
        speed: 8, 
        experience: 0,
        level: 1,
        image: '/CharacterImage/knight.png',
        skills: ['basicAttack'],
        passives: ['Bulwark'],
        status_effects: [],
        playable: true,
        money_drop: 50,
        experience_drop: 50,
        passiveUnlocks: {
          5: 'Retaliate',
        },
      },
      rogue: { 
        id: 'rogue', 
        name: "Rogue", 
        health: 70,
        maxHealth: 70,
        shield: 0,
        damage: 10, 
        speed: 15, 
        experience: 0,
        level: 1,
        image: '/CharacterImage/rogue.png',
        skills: ['basicAttack'],
        passives: ['Dual Wield'],
        status_effects: [],
        playable: true,
        money_drop: 30,
        experience_drop: 40,
        passiveUnlocks: {
          5: 'Sharp Edge',
        },
      },
      mage: { 
        id: 'mage', 
        name: "Mage", 
        health: 50,
        maxHealth: 50,
        shield: 0,
        damage: 25, 
        speed: 12, 
        experience: 0,
        level: 1,
        image: '/CharacterImage/mage.png',
        skills: ['basicAttack'],
        passives: ['Arcane Infused'],
        status_effects: [],
        playable: true,
        money_drop: 40,
        experience_drop: 40,
        passiveUnlocks: {
          5: 'Magic Barrier',
        },
      },
      archer: { 
        id: 'archer', 
        name: "Archer", 
        health: 70,
        maxHealth: 70,
        shield: 0,
        damage: 15, 
        speed: 10, 
        experience: 0,
        level: 1,
        image: '/CharacterImage/archer.png',
        skills: ['basicAttack'],
        passives: ['Poison Tip'],
        status_effects: [],
        playable: true,
        money_drop: 20,
        experience_drop: 50,
        passiveUnlocks: {
          5: 'Weakening Poison',
        },
      },
      vampire: {
        id: 'vampire',
        name: "Vampire",
        health: 50,
        maxHealth: 50,
        shield: 0,
        damage: 20,
        speed: 16,
        experience: 0,
        level: 1,
        image: '/CharacterImage/vampire.png',
        skills: ['basicAttack'],
        passives: ['Life Steal'],
        status_effects: [],
        playable: true,
        money_drop: 45,
        experience_drop: 60,
        passiveUnlocks: {
          5: 'Undead Rage',
        },
      },
      zombie: {
        id: 'zombie',
        name: "Zombie",
        health: 50,
        maxHealth: 50,
        shield: 0,
        damage: 10,
        speed: 5,
        experience: 0,
        level: 1,
        image: '/CharacterImage/zombie.png',
        skills: ['basicAttack'],
        passives: ['Undead Rage'],
        status_effects: [],
        playable: false,
        money_drop: 30,
        experience_drop: 40,
      },
      ghost: {
        id: 'ghost',
        name: "Ghost",
        health: 60,
        maxHealth: 60,
        shield: 0,
        damage: 15,
        speed: 10,
        experience: 0,
        level: 1,
        image: '/CharacterImage/ghost.png',
        skills: ['basicAttack'],
        passives: [],
        status_effects: [],
        playable: false,
        money_drop: 40,
        experience_drop: 50,
      },
      necromancer: {
        id: 'necromancer',
        name: "Necromancer",
        health: 200,
        maxHealth: 200,
        shield: 0,
        damage: 10,
        speed: 10,
        experience: 0,
        level: 1,
        image: '/CharacterImage/necromancer.png',
        skills: ['basicAttack'],
        passives: ['Soul Absorption'],
        status_effects: [],
        playable: false,
        enemy_type: 'Boss',
        money_drop: 120,
        experience_drop: 120,
        passiveUnlocks: {
          5: 'Arcane Infused',
          10: 'Undead Rage',
        },
        lootTable: [
          {name: 'Soul Absorption', passiveId: 'passiveSoulAbsorption', chance: 30 },
        ],
      },
      mimicKing: {
        id: 'mimicKing',
        name: "King Chest Mimic",
        health: 200,
        maxHealth: 200,
        shield: 0,
        damage: 15,
        speed: 1,
        experience: 0,
        level: 1,
        image: '/CharacterImage/mimicKing.png',
        skills: ['basicAttack'],
        passives: ['Chest Mimic'],
        status_effects: [],
        playable: false,
        enemy_type: 'Mini Boss',
        money_drop: 1000,
        experience_drop: 0,
        passiveUnlocks: {
          5: 'Sharp Edge',
        },
      },
      archmage: {
        id: 'archmage',
        name: "Archmage",
        health: 100,
        maxHealth: 100,
        shield: 0,
        damage: 10,
        speed: 1,
        experience: 0,
        level: 1,
        image: '/CharacterImage/archmage.png',
        skills: ['basicAttack'],
        passives: ['Archmage Codex'],
        status_effects: [],
        playable: false,
        enemy_type: 'Mini Boss',
        money_drop: 100,
        experience_drop: 500,
        passiveUnlocks: {
          5: 'Arcane Infused',
          10: 'Weakening Poison',
        },
      },
      theLich: {
        id: 'theLich',
        name: "The Lich",
        health: 50,
        maxHealth: 50,
        shield: 0,
        damage: 5,
        speed: 1,
        experience: 0,
        level: 1,
        image: '/CharacterImage/theLich.png',
        skills: ['basicAttack'],
        passives: ['Eternal Suffering'],
        status_effects: [],
        playable: false,
        enemy_type: 'Raid Boss',
        money_drop: 0,
        experience_drop: 0,
      },
  };