export const characterList = {
  // Dummy: {
  //   id: 'dummy',
  //   name: "Dummy",
  //   health: 200,
  //   maxHealth: 200,
  //   damage: 0,
  //   speed: 1,
  //   image: '/CharacterImage/dummy.png',
  //   skills: ['basicAttack'],
  //   passives: [],
  //   isAlive: true,
  //   status_effects: [],
  //   money_drop: 0,
  // },
  knight: { 
      id: 'knight', 
      name: "Knight", 
      health: 80,
      maxHealth: 80,
      damage: 15, 
      speed: 8, 
      image: '/CharacterImage/knight.png',
      skills: ['basicAttack'],
      passives: ['Bulwark'],
      isAlive: true,
      status_effects: [],
      money_drop: 50
    },
    archer: { 
      id: 'archer', 
      name: "Archer", 
      health: 70,
      maxHealth: 70,
      damage: 15, 
      speed: 10, 
      image: '/CharacterImage/archer.png',
      skills: ['basicAttack'],
      passives: ['Poison Tip'],
      isAlive: true,
      status_effects: [],
      money_drop: 20,
    },
    mage: { 
      id: 'mage', 
      name: "Mage", 
      health: 60,
      maxHealth: 60,
      damage: 25, 
      speed: 12, 
      image: '/CharacterImage/mage.png',
      skills: ['basicAttack'],
      passives: ['Arcane Infused'],
      isAlive: true,
      status_effects: [],
      money_drop: 40,
    },
    rouge: { 
      id: 'rouge', 
      name: "Rouge", 
      health: 70,
      maxHealth: 70,
      damage: 10, 
      speed: 15, 
      image: '/CharacterImage/rouge.png',
      skills: ['doubleAttack'],
      passives: ['Dual Wield'],
      isAlive: true,
      status_effects: [],
      money_drop: 30,
    },
    vampire: {
      id: 'vampire',
      name: "Vampire",
      health: 50,
      maxHealth: 50,
      damage: 20,
      speed: 16,
      image: '/CharacterImage/vampire.png',
      skills: ['basicAttack'],
      passives: ['Life Steal'],
      isAlive: true,
      status_effects: [],
      money_drop: 45,
    },
};