export const passiveDescriptions = [
    { name: 'Bulwark', description: 'Reduce incoming damage by half' },
    { name: 'Dual Wield', description: 'Attacks twice in one turn, the second hit does 50% less damage' },
    { name: 'Arcane Infused', description: 'Ignores damage reduction effects' },
    { name: 'Life Steal', description: 'Heals 50% of damage done' },
    { name: 'Poison Tip', description: 'Applies a 2 turns poison on hit' },
    { name: 'Soul Absorption', description: 'Gains souls upon attacking, launches Soul Barrage at max stacks hitting 3 times and healing!' },
    { name: 'Chest Mimic', description: 'Drops 10 coins when attacked.' },
    { name: 'Retaliate', description: 'Deals half of own damage to attacker when hit.' },
    { name: 'Sharp Edge', description: 'Inflicts 2 turns bleed on hit.' },
    { name: 'Magic Barrier', description: 'Gains 50% of health as shield at the start of combat.' },
    { name: 'Archmage Codex', description: 'Gains Archmage Codex which cycles between modes and replaces basic attack.\n<u>Arcane Assault</u>: Attacks 3 times\n<u>Mystic Aegis</u>: Gives self 50% of max hp as shield\n<u>Venom Verse</u>: Inflicts 3 poisons on the enemy' },
    { name: 'Undead Rage', description: 'At/below 30% of max health after attacked, gains 50% of max health as Shield and Damage Up for 3 turns. Once per battle.' },
    { name: 'Weakening Poison', description: 'Poison effect on the opponent decreases their damage by 25%' },
    { name: 'Eternal Suffering', description: 'Gains Necrotic everytime this unit is revived.\nNecrotic: Each stack increases damage by 5% of enemy max health. Will not dissapear when reviving.' },
  ];